// PRODUCT TYPE ACTIONS
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'
export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'
export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'
export const SET_SELECTED_PRODUCT_ID = 'SET_SELECTED_PRODUCT_ID'
export const FILTER_PRODUCTS_BY_SIZE = 'FILTER_PRODUCTS_BY_SIZE'
export const ORDER_PRODUCTS_BY_PRICE = 'ORDER_PRODUCTS_BY_PRICE'
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'

// CATEGORIE TYPE ACTIONS
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'

// USER TYPE ACTIONS
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const ADD_USER_PENDING = 'ADD_USER_PENDING'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'
export const IS_AUTH = 'IS_AUTH'
export const FORGOT_PASSWORD_FETCHING = 'FORGOT_PASSWORD_FETCHING'
export const FORGOT_PASSWORD_REJECTED = 'FORGOT_PASSWORD_REJECTED'
export const FORGOT_PASSWORD_FULFILLED = 'FORGOT_PASSWORD_FULFILLED'
export const CHANGE_PASSWORD_FETCHING = 'CHANGE_PASSWORD_FETCHING'
export const CHANGE_PASSWORD_FULFILLED = 'CHANGE_PASSWORD_FULFILLED'
export const CHANGE_PASSWORD_REJECTED = 'CHANGE_PASSWORD_REJECTED'
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD'
export const SET_MAIL_SENDED = 'SET_MAIL_SENDED'
export const FETCH_USERS = 'FETCH_USERS'

// CART TYPE ACTIONS
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAN_CART = 'CLEAN_CART'

// SALES TYPE ACTIONS
export const FETCH_SALES = 'FETCH_SALES'
export const GET_ORDER_FULFILLED = 'GET_ORDER_FULFILLED'
export const POST_ORDER_FETCHING = 'POST_ORDER_FETCHING'
export const POST_ORDER_FULFILLED = 'POST_ORDER_FULFILLED'
export const POST_ORDER_REJECTED = 'POST_ORDER_REJECTED'
export const ORDER_CANCEL_FETCHING = 'ORDER_CANCEL_FETCHING'
export const ORDER_CANCEL_FULFILLED = 'ORDER_CANCEL_FULFILLED'
export const ORDER_CANCEL_REJECTED = 'ORDER_CANCEL_REJECTED'

// MERCADOPAGO TYPE ACTIONS
export const MERCADOPAGO_SUCCESS = 'MERCADOPAGO_SUCCESS'
export const MERCADOPAGO_PENDING = 'MERCADOPAGO_PENDING'
export const MERCADOPAGO_ERROR = 'MERCADOPAGO_ERROR'

// PUBLICITY TYPE ACTIONS
export const POST_PUBLICITY_ONE_FETCHING = 'POST_PUBLICITY_ONE_FETCHING'
export const POST_PUBLICITY_ONE_FULFILLED = 'POST_PUBLICITY_ONE_FULFILLED'
export const POST_PUBLICITY_ONE_REJECTED = 'POST_PUBLICITY_ONE_REJECTED'

export const UPDATE_PUBLICITY_ONE_FETCHING = 'UPDATE_PUBLICITY_ONE_FETCHING'
export const UPDATE_PUBLICITY_ONE_FULFILLED = 'UPDATE_PUBLICITY_ONE_FULFILLED'
export const UPDATE_PUBLICITY_ONE_REJECTED = 'UPDATE_PUBLICITY_ONE_REJECTED'

export const REMOVE_PUBLICITY_ONE_FETCHING = 'REMOVE_PUBLICITY_ONE_FETCHING'
export const REMOVE_PUBLICITY_ONE_FULFILLED = 'REMOVE_PUBLICITY_ONE_FULFILLED'
export const REMOVE_PUBLICITY_ONE_REJECTED = 'REMOVE_PUBLICITY_ONE_REJECTED'

export const GET_PUBLICITY_ONE_FETCHING = 'GET_PUBLICITY_ONE_FETCHING'
export const GET_PUBLICITY_ONE_FULFILLED = 'GET_PUBLICITY_ONE_FULFILLED'
export const GET_PUBLICITY_ONE_REJECTED = 'GET_PUBLICITY_ONE_REJECTED'

export const POST_PUBLICITY_TWO_FETCHING = 'POST_PUBLICITY_TWO_FETCHING'
export const POST_PUBLICITY_TWO_FULFILLED = 'POST_PUBLICITY_TWO_FULFILLED'
export const POST_PUBLICITY_TWO_REJECTED = 'POST_PUBLICITY_TWO_REJECTED'

export const UPDATE_PUBLICITY_TWO_FETCHING = 'UPDATE_PUBLICITY_TWO_FETCHING'
export const UPDATE_PUBLICITY_TWO_FULFILLED = 'UPDATE_PUBLICITY_TWO_FULFILLED'
export const UPDATE_PUBLICITY_TWO_REJECTED = 'UPDATE_PUBLICITY_TWO_REJECTED'

export const REMOVE_PUBLICITY_TWO_FETCHING = 'REMOVE_PUBLICITY_TWO_FETCHING'
export const REMOVE_PUBLICITY_TWO_FULFILLED = 'REMOVE_PUBLICITY_TWO_FULFILLED'
export const REMOVE_PUBLICITY_TWO_REJECTED = 'REMOVE_PUBLICITY_TWO_REJECTED'

export const GET_PUBLICITY_TWO_FETCHING = 'GET_PUBLICITY_TWO_FETCHING'
export const GET_PUBLICITY_TWO_FULFILLED = 'GET_PUBLICITY_TWO_FULFILLED'
export const GET_PUBLICITY_TWO_REJECTED = 'GET_PUBLICITY_TWO_REJECTED'

export const POST_PUBLICITY_THIRD_FETCHING = 'POST_PUBLICITY_THIRD_FETCHING'
export const POST_PUBLICITY_THIRD_FULFILLED = 'POST_PUBLICITY_THIRD_FULFILLED'
export const POST_PUBLICITY_THIRD_REJECTED = 'POST_PUBLICITY_THIRD_REJECTED'

export const UPDATE_PUBLICITY_THIRD_FETCHING = 'UPDATE_PUBLICITY_THIRD_FETCHING'
export const UPDATE_PUBLICITY_THIRD_FULFILLED = 'UPDATE_PUBLICITY_THIRD_FULFILLED'
export const UPDATE_PUBLICITY_THIRD_REJECTED = 'UPDATE_PUBLICITY_THIRD_REJECTED'

export const REMOVE_PUBLICITY_THIRD_FETCHING = 'REMOVE_PUBLICITY_THIRD_FETCHING'
export const REMOVE_PUBLICITY_THIRD_FULFILLED = 'REMOVE_PUBLICITY_THIRD_FULFILLED'
export const REMOVE_PUBLICITY_THIRD_REJECTED = 'REMOVE_PUBLICITY_THIRD_REJECTED'

export const GET_PUBLICITY_THIRD_FETCHING = 'GET_PUBLICITY_THIRD_FETCHING'
export const GET_PUBLICITY_THIRD_FULFILLED = 'GET_PUBLICITY_THIRD_FULFILLED'
export const GET_PUBLICITY_THIRD_REJECTED = 'GET_PUBLICITY_THIRD_REJECTED'

export const POST_PUBLICITY_FOURTH_FETCHING = 'POST_PUBLICITY_FOURTH_FETCHING'
export const POST_PUBLICITY_FOURTH_FULFILLED = 'POST_PUBLICITY_FOURTH_FULFILLED'
export const POST_PUBLICITY_FOURTH_REJECTED = 'POST_PUBLICITY_FOURTH_REJECTED'

export const UPDATE_PUBLICITY_FOURTH_FETCHING = 'UPDATE_PUBLICITY_FOURTH_FETCHING'
export const UPDATE_PUBLICITY_FOURTH_FULFILLED = 'UPDATE_PUBLICITY_FOURTH_FULFILLED'
export const UPDATE_PUBLICITY_FOURTH_REJECTED = 'UPDATE_PUBLICITY_FOURTH_REJECTED'

export const REMOVE_PUBLICITY_FOURTH_FETCHING = 'REMOVE_PUBLICITY_FOURTH_FETCHING'
export const REMOVE_PUBLICITY_FOURTH_FULFILLED = 'REMOVE_PUBLICITY_FOURTH_FULFILLED'
export const REMOVE_PUBLICITY_FOURTH_REJECTED = 'REMOVE_PUBLICITY_FOURTH_REJECTED'

export const GET_PUBLICITY_FOURTH_FETCHING = 'GET_PUBLICITY_FOURTH_FETCHING'
export const GET_PUBLICITY_FOURTH_FULFILLED = 'GET_PUBLICITY_FOURTH_FULFILLED'
export const GET_PUBLICITY_FOURTH_REJECTED = 'GET_PUBLICITY_FOURTH_REJECTED'

export const POST_PUBLICITY_FIVE_FETCHING = 'POST_PUBLICITY_FIVE_FETCHING'
export const POST_PUBLICITY_FIVE_FULFILLED = 'POST_PUBLICITY_FIVE_FULFILLED'
export const POST_PUBLICITY_FIVE_REJECTED = 'POST_PUBLICITY_FIVE_REJECTED'

export const UPDATE_PUBLICITY_FIVE_FETCHING = 'UPDATE_PUBLICITY_FIVE_FETCHING'
export const UPDATE_PUBLICITY_FIVE_FULFILLED = 'UPDATE_PUBLICITY_FIVE_FULFILLED'
export const UPDATE_PUBLICITY_FIVE_REJECTED = 'UPDATE_PUBLICITY_FIVE_REJECTED'

export const REMOVE_PUBLICITY_FIVE_FETCHING = 'REMOVE_PUBLICITY_FIVE_FETCHING'
export const REMOVE_PUBLICITY_FIVE_FULFILLED = 'REMOVE_PUBLICITY_FIVE_FULFILLED'
export const REMOVE_PUBLICITY_FIVE_REJECTED = 'REMOVE_PUBLICITY_FIVE_REJECTED'

export const GET_PUBLICITY_FIVE_FETCHING = 'GET_PUBLICITY_FIVE_FETCHING'
export const GET_PUBLICITY_FIVE_FULFILLED = 'GET_PUBLICITY_FIVE_FULFILLED'
export const GET_PUBLICITY_FIVE_REJECTED = 'GET_PUBLICITY_FIVE_REJECTED'

